name: Integral CI

on:
  push:
    branches: [ "Integral" ]
  pull_request:
    branches: [ "Integral" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y build-essential clang-format

      - name: Check Formatting
        run: |
          cd Integral
          make check_fmt

      - name: Build and Run Tests
        run: |
          cd Integral
          make all
          make test
